var searchData=
[
  ['x',['x',['../de/da3/structnana_1_1basic__point.html#a426488d5403a0fd60ac16adaedbe9a58',1,'nana::basic_point::x()'],['../dd/d2d/structnana_1_1rectangle.html#a86bab619f2ca4168249f282f189bb3af',1,'nana::rectangle::x()'],['../da/dfe/structnana_1_1arg__move.html#a24d577f04036e9b1fc08cac0c8bc84fe',1,'nana::arg_move::x()'],['../d4/d00/structnana_1_1detail_1_1msg__packet__tag.html#aba557973a9466ac5ab5a41f5841a8ddf',1,'nana::detail::msg_packet_tag::x()'],['../d3/d59/classnana_1_1rectangle__rotator.html#a84c51a5edee90cd4aa4d013b8f013038',1,'nana::rectangle_rotator::x()']]],
  ['x_5ficon',['x_icon',['../d3/ddd/classnana_1_1element_1_1x__icon.html',1,'nana::element']]],
  ['x_5ficon',['x_icon',['../d6/d63/classnana_1_1element__manager.html#ad616f2da13ee2d205e21dfb0d908336c',1,'nana::element_manager::x_icon(const std::string &amp;name, const pat::cloneable&lt; element::provider::factory_interface&lt; element::element_interface &gt;&gt; &amp;factory)'],['../d6/d63/classnana_1_1element__manager.html#aa43fa7d530fe552638b61b0a1fe170cf',1,'nana::element_manager::x_icon(const std::string &amp;name) const ']]],
  ['x_5ficon_5f',['x_icon_',['../d3/ddf/classnana_1_1place__parts_1_1dockcaption__dtrigger.html#a755aad0d7464f25e513a81d857e162b6',1,'nana::place_parts::dockcaption_dtrigger']]],
  ['x_5fpointed_5f',['x_pointed_',['../d3/ddf/classnana_1_1place__parts_1_1dockcaption__dtrigger.html#adc98830cf38ec0a01f1b944f3ba6a69a',1,'nana::place_parts::dockcaption_dtrigger']]],
  ['x_5fref',['x_ref',['../d3/d59/classnana_1_1rectangle__rotator.html#a1463bb8ba87bc0339b02244234556cbb',1,'nana::rectangle_rotator']]],
  ['x_5fstate_5f',['x_state_',['../d3/ddf/classnana_1_1place__parts_1_1dockcaption__dtrigger.html#a5e973e8bccb37538d61ad4989b6b8fd5',1,'nana::place_parts::dockcaption_dtrigger']]],
  ['xalloc',['xalloc',['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_ofstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::fstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_ostringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_ios::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ostringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_fstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::iostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ios_base::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wistream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::stringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wifstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_istream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::strstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_stringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wostringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::istrstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_ostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wiostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ofstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_istringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_ifstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::istringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::istream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ostrstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wfstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_iostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wofstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wstringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wistringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ifstream::xalloc()']]],
  ['xdnd_5fdata',['xdnd_data',['../db/d47/structnana_1_1detail_1_1xdnd__data.html',1,'nana::detail']]],
  ['xdnd_5fprotocol',['xdnd_protocol',['../d5/dcc/classnana_1_1detail_1_1xdnd__protocol.html#aab99603edabf226e550587af5257315d',1,'nana::detail::xdnd_protocol']]],
  ['xdnd_5fprotocol',['xdnd_protocol',['../d5/dcc/classnana_1_1detail_1_1xdnd__protocol.html',1,'nana::detail']]],
  ['xdnd_5fstatus_5fstate',['xdnd_status_state',['../d5/dcc/classnana_1_1detail_1_1xdnd__protocol.html#acc7fc1fae3e117fcbb2b97fb5fbed902',1,'nana::detail::xdnd_protocol']]],
  ['xevent',['xevent',['../d4/d00/structnana_1_1detail_1_1msg__packet__tag.html#aacae9305e1c4af2858af0b06a1ac0746',1,'nana::detail::msg_packet_tag::xevent()'],['../d4/d00/structnana_1_1detail_1_1msg__packet__tag.html#a30cfddba8a07fa8ffec0db674058ff3aa326fb0f89efbce716b1eb15813cd1010',1,'nana::detail::msg_packet_tag::xevent()']]],
  ['xsgetn',['xsgetn',['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::basic_filebuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::wstringbuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::stringbuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::wfilebuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::wstreambuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::strstreambuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::basic_stringbuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::basic_streambuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::filebuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::streambuf::xsgetn()']]],
  ['xsputn',['xsputn',['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::basic_filebuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::wstringbuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::stringbuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::wfilebuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::wstreambuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::strstreambuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::basic_stringbuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::basic_streambuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::filebuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::streambuf::xsputn()']]]
];
