var searchData=
[
  ['va_5flist',['va_list',['http://en.cppreference.com/w/cpp/utility/variadic/va_list.html',1,'']]],
  ['valarray',['valarray',['http://en.cppreference.com/w/cpp/numeric/valarray.html',1,'std']]],
  ['value',['value',['../d9/df6/structnana_1_1date_1_1value.html',1,'nana::date']]],
  ['value',['value',['../de/d89/structnana_1_1time_1_1value.html',1,'nana::time']]],
  ['value_5fcompare',['value_compare',['http://en.cppreference.com/w/cpp/container/multimap/value_compare.html',1,'std::multimap']]],
  ['value_5fcompare',['value_compare',['http://en.cppreference.com/w/cpp/container/map/value_compare.html',1,'std::map']]],
  ['vector',['vector',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20_3a_3astd_3a_3astring_20_3e',['vector&lt; ::std::string &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20basic_5fwindow_20_2a_20_3e',['vector&lt; basic_window * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20cell_20_3e',['vector&lt; cell &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20column_5ft_20_3e',['vector&lt; column_t &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20drag_5ftarget_5ft_20_3e',['vector&lt; drag_target_t &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20dynamic_5fdrawing_3a_3aobject_20_2a_20_3e',['vector&lt; dynamic_drawing::object * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20element_5fstate_20_3e',['vector&lt; element_state &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20element_5ftag_20_3e',['vector&lt; element_tag &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20handle_5ftype_20_3e',['vector&lt; handle_type &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20item_5ftype_20_2a_20_3e',['vector&lt; item_type * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20item_5ftype_20_3e',['vector&lt; item_type &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20iterator_20_3e',['vector&lt; iterator &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20key_5fvalue_5frep_20_3e',['vector&lt; key_value_rep &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20line_5fmetrics_20_3e',['vector&lt; line_metrics &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20nana_3a_3aanimation_3a_3aimpl_20_2a_20_3e',['vector&lt; nana::animation::impl * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20nana_3a_3aanimation_3a_3aperformance_5fmanager_3a_3athread_5fvariable_20_2a_20_3e',['vector&lt; nana::animation::performance_manager::thread_variable * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20nana_3a_3adetail_3a_3abasic_5fwindow_20_2a_20_3e',['vector&lt; nana::detail::basic_window * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20nana_3a_3adetail_3a_3abasic_5fwindow_3a_3aedge_5fnimbus_5faction_20_3e',['vector&lt; nana::detail::basic_window::edge_nimbus_action &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20nana_3a_3adetail_3a_3anative_5fwindow_5fhandle_5fimpl_20_3e',['vector&lt; nana::detail::native_window_handle_impl &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20nana_3a_3adrawerbase_3a_3alistbox_3a_3acell_20_3e',['vector&lt; nana::drawerbase::listbox::cell &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20nana_3a_3adrawerbase_3a_3amenu_3a_3amenu_5fitem_5ftype_20_3e',['vector&lt; nana::drawerbase::menu::menu_item_type &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20nana_3a_3adrawerbase_3a_3amenu_3a_3amenu_5ftype_20_2a_20_3e',['vector&lt; nana::drawerbase::menu::menu_type * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20nana_3a_3afilebox_3a_3aimplement_3a_3afilter_20_3e',['vector&lt; nana::filebox::implement::filter &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20nana_3a_3anana_3a_3apoint_20_3e',['vector&lt; nana::nana::point &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20nana_3a_3anana_3a_3asize_20_3e',['vector&lt; nana::nana::size &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20nana_3a_3anana_3a_3aunicode_5fbidi_3a_3aentity_20_3e',['vector&lt; nana::nana::unicode_bidi::entity &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20nana_3a_3aplace_3a_3aimplement_3a_3afield_5fgather_3a_3aelement_5ft_20_3e',['vector&lt; nana::place::implement::field_gather::element_t &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20nana_3a_3aplace_5fparts_3a_3anumber_5ft_20_3e',['vector&lt; nana::place_parts::number_t &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20nana_3a_3areal_5fdisplay_20_3e',['vector&lt; nana::real_display &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20nana_3a_3arectangle_20_3e',['vector&lt; nana::rectangle &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20nana_3a_3aunicode_5fbidi_3a_3aentity_20_3e',['vector&lt; nana::unicode_bidi::entity &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20nana_3a_3aupoint_20_3e',['vector&lt; nana::upoint &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20nana_3a_3awidgets_3a_3askeletons_3a_3aentity_20_3e',['vector&lt; nana::widgets::skeletons::entity &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20nana_3a_3awidgets_3a_3askeletons_3a_3afblock_20_2a_20_3e',['vector&lt; nana::widgets::skeletons::fblock * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20pixel_5ftag_20_3e',['vector&lt; pixel_tag &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20pool_5fthrobj_20_2a_20_3e',['vector&lt; pool_throbj * &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20size_5ftype_20_3e',['vector&lt; size_type &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3afunction_3c_20void_28command_2c_20const_20std_3a_3astring_20_26_29_3e_20_3e',['vector&lt; std::function&lt; void(command, const std::string &amp;)&gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3apair_20_3e',['vector&lt; std::pair &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3apair_3c_20element_5ftype_20_2a_2c_20cloneable_3c_20element_3a_3adetail_3a_3afactory_5fabstract_20_3e_20_3e_20_3e',['vector&lt; std::pair&lt; element_type *, cloneable&lt; element::detail::factory_abstract &gt; &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3apair_3c_20index_5ftype_2c_20nana_3a_3adrawerbase_3a_3alistbox_3a_3aessence_5ft_3a_3ainline_5fpane_20_2a_20_3e_20_3e',['vector&lt; std::pair&lt; index_type, nana::drawerbase::listbox::essence_t::inline_pane * &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3apair_3c_20nana_3a_3adetail_3a_3abasic_5fwindow_20_2a_2c_20bool_20_3e_20_3e',['vector&lt; std::pair&lt; nana::detail::basic_window *, bool &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20nana_3a_3adrawerbase_3a_3acombox_3a_3aitem_20_3e_20_3e',['vector&lt; std::shared_ptr&lt; nana::drawerbase::combox::item &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3ashared_5fptr_3c_20nana_3a_3adrawerbase_3a_3afloat_5flistbox_3a_3aitem_5finterface_20_3e_20_3e',['vector&lt; std::shared_ptr&lt; nana::drawerbase::float_listbox::item_interface &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3asize_5ft_20_3e',['vector&lt; std::size_t &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3astring_20_3e',['vector&lt; std::string &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3aunique_5fptr_3c_20eval_5farg_20_3e_20_3e',['vector&lt; std::unique_ptr&lt; eval_arg &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3aunique_5fptr_3c_20nana_3a_3acheckbox_20_3e_20_3e',['vector&lt; std::unique_ptr&lt; nana::checkbox &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3aunique_5fptr_3c_20nana_3a_3anana_3a_3awidget_20_3e_20_3e',['vector&lt; std::unique_ptr&lt; nana::nana::widget &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3aunique_5fptr_3c_20nana_3a_3aplace_3a_3aimplement_3a_3adivision_20_3e_20_3e',['vector&lt; std::unique_ptr&lt; nana::place::implement::division &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20std_3a_3aunique_5fptr_3c_20widget_5fholder_20_3e_20_3e',['vector&lt; std::unique_ptr&lt; widget_holder &gt; &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20text_5fsection_20_3e',['vector&lt; text_section &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20thr_5frefcnt_20_3e',['vector&lt; thr_refcnt &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20trigger_5ft_20_3e',['vector&lt; trigger_t &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]],
  ['vector_3c_20unsigned_20long_20_3e',['vector&lt; unsigned long &gt;',['http://en.cppreference.com/w/cpp/container/vector.html',1,'std']]]
];
