var searchData=
[
  ['u16streampos',['u16streampos',['http://en.cppreference.com/w/cpp/io/fpos.html',1,'std']]],
  ['u16string',['u16string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std']]],
  ['u32streampos',['u32streampos',['http://en.cppreference.com/w/cpp/io/fpos.html',1,'std']]],
  ['u32string',['u32string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std']]],
  ['uframes',['uframes',['../df/d8f/unionnana_1_1frame_1_1uframes.html',1,'nana::frame']]],
  ['ui_5felement',['ui_element',['../dd/dab/structnana_1_1drawerbase_1_1categorize_1_1renderer_1_1ui__element.html',1,'nana::drawerbase::categorize::renderer']]],
  ['uint16_5ft',['uint16_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint32_5ft',['uint32_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint64_5ft',['uint64_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint8_5ft',['uint8_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast16_5ft',['uint_fast16_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast32_5ft',['uint_fast32_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast64_5ft',['uint_fast64_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5ffast8_5ft',['uint_fast8_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast16_5ft',['uint_least16_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast32_5ft',['uint_least32_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast64_5ft',['uint_least64_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uint_5fleast8_5ft',['uint_least8_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uintmax_5ft',['uintmax_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['uintptr_5ft',['uintptr_t',['http://en.cppreference.com/w/cpp/types/integer.html',1,'std']]],
  ['unary_5ffunction',['unary_function',['http://en.cppreference.com/w/cpp/utility/functional/unary_function.html',1,'std']]],
  ['unary_5fnegate',['unary_negate',['http://en.cppreference.com/w/cpp/utility/functional/unary_negate.html',1,'std']]],
  ['underflow_5ferror',['underflow_error',['http://en.cppreference.com/w/cpp/error/underflow_error.html',1,'std']]],
  ['underlying_5ftype',['underlying_type',['http://en.cppreference.com/w/cpp/types/underlying_type.html',1,'std']]],
  ['undo_5fbackspace',['undo_backspace',['../d4/dc4/classnana_1_1widgets_1_1skeletons_1_1text__editor_1_1undo__backspace.html',1,'nana::widgets::skeletons::text_editor']]],
  ['undo_5finput_5ftext',['undo_input_text',['../df/da7/classnana_1_1widgets_1_1skeletons_1_1text__editor_1_1undo__input__text.html',1,'nana::widgets::skeletons::text_editor']]],
  ['undo_5fmove_5ftext',['undo_move_text',['../d1/d97/classnana_1_1widgets_1_1skeletons_1_1text__editor_1_1undo__move__text.html',1,'nana::widgets::skeletons::text_editor']]],
  ['undoable',['undoable',['../d2/d33/classnana_1_1widgets_1_1skeletons_1_1undoable.html',1,'nana::widgets::skeletons']]],
  ['undoable_3c_20command_20_3e',['undoable&lt; command &gt;',['../d2/d33/classnana_1_1widgets_1_1skeletons_1_1undoable.html',1,'nana::widgets::skeletons']]],
  ['undoable_5fcommand_5finterface',['undoable_command_interface',['../df/da3/classnana_1_1widgets_1_1skeletons_1_1undoable__command__interface.html',1,'nana::widgets::skeletons']]],
  ['undoable_5fcommand_5finterface_3c_20command_20_3e',['undoable_command_interface&lt; command &gt;',['../df/da3/classnana_1_1widgets_1_1skeletons_1_1undoable__command__interface.html',1,'nana::widgets::skeletons']]],
  ['unexpected_5fhandler',['unexpected_handler',['http://en.cppreference.com/w/cpp/error/unexpected_handler.html',1,'std']]],
  ['unicode_5fbidi',['unicode_bidi',['../d8/d7f/classnana_1_1unicode__bidi.html',1,'nana']]],
  ['uniform_5fint_5fdistribution',['uniform_int_distribution',['http://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution.html',1,'std']]],
  ['uniform_5freal_5fdistribution',['uniform_real_distribution',['http://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution.html',1,'std']]],
  ['unique_5flock',['unique_lock',['http://en.cppreference.com/w/cpp/thread/unique_lock.html',1,'std']]],
  ['unique_5fptr',['unique_ptr',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20char_5b_5d_3e',['unique_ptr&lt; char[]&gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20drawerbase_3a_3anana_3a_3atabbar_3a_3aevent_5fagent_3c_20value_5ftype_2c_20drawerbase_3a_3anana_3a_3atabbar_3a_3atrigger_20_3e_20_3e',['unique_ptr&lt; drawerbase::nana::tabbar::event_agent&lt; value_type, drawerbase::nana::tabbar::trigger &gt; &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20element_3a_3abground_20_3e',['unique_ptr&lt; element::bground &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20format_20_3e',['unique_ptr&lt; format &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20inline_5fwidget_20_3e',['unique_ptr&lt; inline_widget &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3adetail_3a_3ainline_5fwidget_5fnotifier_5finterface_20_3e',['unique_ptr&lt; nana::detail::inline_widget_notifier_interface &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3adetail_3a_3awidget_5fnotifier_5finterface_20_3e',['unique_ptr&lt; nana::detail::widget_notifier_interface &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3adrawerbase_3a_3acategorize_3a_3aevent_5fagent_5finterface_20_3e',['unique_ptr&lt; nana::drawerbase::categorize::event_agent_interface &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3adrawerbase_3a_3acheckbox_3a_3adrawer_3a_3aimplement_20_3e',['unique_ptr&lt; nana::drawerbase::checkbox::drawer::implement &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3adrawerbase_3a_3acombox_3a_3aevent_5fagent_20_3e',['unique_ptr&lt; nana::drawerbase::combox::event_agent &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3adrawerbase_3a_3aspinbox_3a_3aevent_5fagent_20_3e',['unique_ptr&lt; nana::drawerbase::spinbox::event_agent &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3adrawerbase_3a_3aspinbox_3a_3arange_5finterface_20_3e',['unique_ptr&lt; nana::drawerbase::spinbox::range_interface &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3adrawerbase_3a_3atextbox_3a_3aevent_5fagent_20_3e',['unique_ptr&lt; nana::drawerbase::textbox::event_agent &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3aform_20_3e',['unique_ptr&lt; nana::form &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3agroup_3a_3aimplement_20_3e',['unique_ptr&lt; nana::group::implement &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3ainputbox_3a_3adate_3a_3aimplement_20_3e',['unique_ptr&lt; nana::inputbox::date::implement &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3ainputbox_3a_3ainteger_3a_3aimplement_20_3e',['unique_ptr&lt; nana::inputbox::integer::implement &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3ainputbox_3a_3apath_3a_3aimplement_20_3e',['unique_ptr&lt; nana::inputbox::path::implement &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3ainputbox_3a_3areal_3a_3aimplement_20_3e',['unique_ptr&lt; nana::inputbox::real::implement &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3ainputbox_3a_3atext_3a_3aimplement_20_3e',['unique_ptr&lt; nana::inputbox::text::implement &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3anana_3a_3aany_20_3e',['unique_ptr&lt; nana::nana::any &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3anana_3a_3ascroll_3c_20false_20_3e_20_3e',['unique_ptr&lt; nana::nana::scroll&lt; false &gt; &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3anana_3a_3ascroll_3c_20true_20_3e_20_3e',['unique_ptr&lt; nana::nana::scroll&lt; true &gt; &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3apanel_3c_20true_20_3e_20_3e',['unique_ptr&lt; nana::panel&lt; true &gt; &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3apat_3a_3aabstract_5ffactory_20_3e',['unique_ptr&lt; nana::pat::abstract_factory &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3aplace_3a_3aimplement_3a_3adivision_20_3e',['unique_ptr&lt; nana::place::implement::division &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3atabbar_5flite_20_3e',['unique_ptr&lt; nana::tabbar_lite &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3atooltip_5finterface_2c_20std_3a_3afunction_20_3e',['unique_ptr&lt; nana::tooltip_interface, std::function &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3awidget_20_3e',['unique_ptr&lt; nana::widget &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3awidgets_3a_3askeletons_3a_3atext_5feditor_3a_3aeditor_5fbehavior_5finterface_20_3e',['unique_ptr&lt; nana::widgets::skeletons::text_editor::editor_behavior_interface &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20nana_3a_3awidgets_3a_3askeletons_3a_3atext_5feditor_3a_3akeywords_20_3e',['unique_ptr&lt; nana::widgets::skeletons::text_editor::keywords &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20paint_3a_3atext_5frenderer_20_3e',['unique_ptr&lt; paint::text_renderer &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20place_5fparts_3a_3adockarea_20_3e',['unique_ptr&lt; place_parts::dockarea &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20scheme_5ftype_20_3e',['unique_ptr&lt; scheme_type &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20std_3a_3athread_20_3e',['unique_ptr&lt; std::thread &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unique_5fptr_3c_20std_3a_3avector_3c_20std_3a_3aunique_5fptr_3c_20docker_20_3e_20_3e_20_3e',['unique_ptr&lt; std::vector&lt; std::unique_ptr&lt; docker &gt; &gt; &gt;',['http://en.cppreference.com/w/cpp/memory/unique_ptr.html',1,'std']]],
  ['unordered_5fmap',['unordered_map',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmap_3c_20nana_3a_3adetail_3a_3anative_5fwindow_5fhandle_5fimpl_2c_20window_5fnotifiers_20_3e',['unordered_map&lt; nana::detail::native_window_handle_impl, window_notifiers &gt;',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmap_3c_20nana_3a_3adetail_3a_3awindow_5fhandle_5fimpl_2c_20std_3a_3ashared_5fptr_3c_20nana_3a_3ageneral_5fevents_20_3e_20_3e',['unordered_map&lt; nana::detail::window_handle_impl, std::shared_ptr&lt; nana::general_events &gt; &gt;',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmap_3c_20std_3a_3astd_3a_3astring_2c_20nana_3a_3astd_3a_3astring_20_3e',['unordered_map&lt; std::std::string, nana::std::string &gt;',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmap_3c_20unsigned_20short_2c_20notifier_5fdata_20_3e',['unordered_map&lt; unsigned short, notifier_data &gt;',['http://en.cppreference.com/w/cpp/container/unordered_map.html',1,'std']]],
  ['unordered_5fmultimap',['unordered_multimap',['http://en.cppreference.com/w/cpp/container/unordered_multimap.html',1,'std']]],
  ['unordered_5fmultiset',['unordered_multiset',['http://en.cppreference.com/w/cpp/container/unordered_multiset.html',1,'std']]],
  ['unordered_5fset',['unordered_set',['http://en.cppreference.com/w/cpp/container/unordered_set.html',1,'std']]],
  ['unordered_5fset_3c_20nana_3a_3adetail_3a_3aevent_5fhandle_5fimpl_20_3e',['unordered_set&lt; nana::detail::event_handle_impl &gt;',['http://en.cppreference.com/w/cpp/container/unordered_set.html',1,'std']]],
  ['upoint',['upoint',['../de/d1b/structnana_1_1upoint.html',1,'nana']]],
  ['user_5fdraw_5ffunction',['user_draw_function',['../d7/db0/classnana_1_1detail_1_1dynamic__drawing_1_1user__draw__function.html',1,'nana::detail::dynamic_drawing']]],
  ['uses_5fallocator',['uses_allocator',['http://en.cppreference.com/w/cpp/memory/uses_allocator.html',1,'std']]]
];
