var namespacepip_1_1__vendor_1_1pkg__resources =
[
    [ "py31compat", "df/d92/namespacepip_1_1__vendor_1_1pkg__resources_1_1py31compat.html", null ],
    [ "PEP440Warning", "da/d17/classpip_1_1__vendor_1_1pkg__resources_1_1_p_e_p440_warning.html", null ],
    [ "ResolutionError", "d1/ded/classpip_1_1__vendor_1_1pkg__resources_1_1_resolution_error.html", "d1/ded/classpip_1_1__vendor_1_1pkg__resources_1_1_resolution_error" ],
    [ "VersionConflict", "d2/d23/classpip_1_1__vendor_1_1pkg__resources_1_1_version_conflict.html", "d2/d23/classpip_1_1__vendor_1_1pkg__resources_1_1_version_conflict" ],
    [ "ContextualVersionConflict", "dc/d5e/classpip_1_1__vendor_1_1pkg__resources_1_1_contextual_version_conflict.html", "dc/d5e/classpip_1_1__vendor_1_1pkg__resources_1_1_contextual_version_conflict" ],
    [ "DistributionNotFound", "d9/dd2/classpip_1_1__vendor_1_1pkg__resources_1_1_distribution_not_found.html", "d9/dd2/classpip_1_1__vendor_1_1pkg__resources_1_1_distribution_not_found" ],
    [ "UnknownExtra", "da/d4c/classpip_1_1__vendor_1_1pkg__resources_1_1_unknown_extra.html", null ],
    [ "IMetadataProvider", "dd/db4/classpip_1_1__vendor_1_1pkg__resources_1_1_i_metadata_provider.html", "dd/db4/classpip_1_1__vendor_1_1pkg__resources_1_1_i_metadata_provider" ],
    [ "IResourceProvider", "d2/daf/classpip_1_1__vendor_1_1pkg__resources_1_1_i_resource_provider.html", "d2/daf/classpip_1_1__vendor_1_1pkg__resources_1_1_i_resource_provider" ],
    [ "WorkingSet", "da/d4f/classpip_1_1__vendor_1_1pkg__resources_1_1_working_set.html", "da/d4f/classpip_1_1__vendor_1_1pkg__resources_1_1_working_set" ],
    [ "_ReqExtras", "d9/dd5/classpip_1_1__vendor_1_1pkg__resources_1_1___req_extras.html", "d9/dd5/classpip_1_1__vendor_1_1pkg__resources_1_1___req_extras" ],
    [ "Environment", "de/d79/classpip_1_1__vendor_1_1pkg__resources_1_1_environment.html", "de/d79/classpip_1_1__vendor_1_1pkg__resources_1_1_environment" ],
    [ "ExtractionError", "d8/da4/classpip_1_1__vendor_1_1pkg__resources_1_1_extraction_error.html", null ],
    [ "ResourceManager", "d9/d86/classpip_1_1__vendor_1_1pkg__resources_1_1_resource_manager.html", "d9/d86/classpip_1_1__vendor_1_1pkg__resources_1_1_resource_manager" ],
    [ "NullProvider", "dd/dc4/classpip_1_1__vendor_1_1pkg__resources_1_1_null_provider.html", "dd/dc4/classpip_1_1__vendor_1_1pkg__resources_1_1_null_provider" ],
    [ "EggProvider", "d8/d75/classpip_1_1__vendor_1_1pkg__resources_1_1_egg_provider.html", "d8/d75/classpip_1_1__vendor_1_1pkg__resources_1_1_egg_provider" ],
    [ "DefaultProvider", "d3/d98/classpip_1_1__vendor_1_1pkg__resources_1_1_default_provider.html", "d3/d98/classpip_1_1__vendor_1_1pkg__resources_1_1_default_provider" ],
    [ "EmptyProvider", "d7/d94/classpip_1_1__vendor_1_1pkg__resources_1_1_empty_provider.html", "d7/d94/classpip_1_1__vendor_1_1pkg__resources_1_1_empty_provider" ],
    [ "ZipManifests", "d7/d6e/classpip_1_1__vendor_1_1pkg__resources_1_1_zip_manifests.html", "d7/d6e/classpip_1_1__vendor_1_1pkg__resources_1_1_zip_manifests" ],
    [ "MemoizedZipManifests", "d4/d6f/classpip_1_1__vendor_1_1pkg__resources_1_1_memoized_zip_manifests.html", "d4/d6f/classpip_1_1__vendor_1_1pkg__resources_1_1_memoized_zip_manifests" ],
    [ "ZipProvider", "de/dc9/classpip_1_1__vendor_1_1pkg__resources_1_1_zip_provider.html", "de/dc9/classpip_1_1__vendor_1_1pkg__resources_1_1_zip_provider" ],
    [ "FileMetadata", "d8/d2b/classpip_1_1__vendor_1_1pkg__resources_1_1_file_metadata.html", "d8/d2b/classpip_1_1__vendor_1_1pkg__resources_1_1_file_metadata" ],
    [ "PathMetadata", "dd/d98/classpip_1_1__vendor_1_1pkg__resources_1_1_path_metadata.html", "dd/d98/classpip_1_1__vendor_1_1pkg__resources_1_1_path_metadata" ],
    [ "EggMetadata", "dd/d2f/classpip_1_1__vendor_1_1pkg__resources_1_1_egg_metadata.html", "dd/d2f/classpip_1_1__vendor_1_1pkg__resources_1_1_egg_metadata" ],
    [ "NoDists", "d8/d67/classpip_1_1__vendor_1_1pkg__resources_1_1_no_dists.html", "d8/d67/classpip_1_1__vendor_1_1pkg__resources_1_1_no_dists" ],
    [ "EntryPoint", "dc/d51/classpip_1_1__vendor_1_1pkg__resources_1_1_entry_point.html", "dc/d51/classpip_1_1__vendor_1_1pkg__resources_1_1_entry_point" ],
    [ "Distribution", "d0/ddb/classpip_1_1__vendor_1_1pkg__resources_1_1_distribution.html", "d0/ddb/classpip_1_1__vendor_1_1pkg__resources_1_1_distribution" ],
    [ "EggInfoDistribution", "da/d9a/classpip_1_1__vendor_1_1pkg__resources_1_1_egg_info_distribution.html", null ],
    [ "DistInfoDistribution", "d0/d07/classpip_1_1__vendor_1_1pkg__resources_1_1_dist_info_distribution.html", "d0/d07/classpip_1_1__vendor_1_1pkg__resources_1_1_dist_info_distribution" ],
    [ "RequirementParseError", "d7/d18/classpip_1_1__vendor_1_1pkg__resources_1_1_requirement_parse_error.html", "d7/d18/classpip_1_1__vendor_1_1pkg__resources_1_1_requirement_parse_error" ],
    [ "Requirement", "dd/d48/classpip_1_1__vendor_1_1pkg__resources_1_1_requirement.html", "dd/d48/classpip_1_1__vendor_1_1pkg__resources_1_1_requirement" ]
];