var searchData=
[
  ['x',['x',['../d0/d24/structnana_1_1point.html#af41b47be4303c8713b92abfb9a7863d0',1,'nana::point::x()'],['../de/d1b/structnana_1_1upoint.html#a57fda1bb3bf87335884180c5db286cee',1,'nana::upoint::x()'],['../dd/d2d/structnana_1_1rectangle.html#a86bab619f2ca4168249f282f189bb3af',1,'nana::rectangle::x()'],['../da/dfe/structnana_1_1arg__move.html#a24d577f04036e9b1fc08cac0c8bc84fe',1,'nana::arg_move::x()'],['../d5/d3f/unionnana_1_1detail_1_1event__mask.html#aae3066ebaca43c1719bb998a2b948951',1,'nana::detail::event_mask::x()'],['../d8/d88/structnana_1_1detail_1_1param__mouse.html#a226814dd6a120edf30490ffd8f51a9a9',1,'nana::detail::param_mouse::x()'],['../dd/db0/structnana_1_1detail_1_1param__mouse_3_018_01_4.html#a572c77437f3de1eeaf07efe46e7eb875',1,'nana::detail::param_mouse&lt; 8 &gt;::x()'],['../dc/dfc/structnana_1_1paint_1_1helper_1_1draw__string.html#a0b42c797511fdb6a3fa84c73ef2d3a02',1,'nana::paint::helper::draw_string::x()'],['../da/d8e/structnana_1_1paint_1_1helper_1_1draw__string__omitted.html#ac9de948d2ddec75ade52d81b00ce3d6a',1,'nana::paint::helper::draw_string_omitted::x()'],['../d8/dad/structnana_1_1paint_1_1helper_1_1draw__string__auto__changing__lines.html#a18d9130c84316b51b684bb17f8d38fdf',1,'nana::paint::helper::draw_string_auto_changing_lines::x()'],['../db/de9/structnana_1_1paint_1_1helper_1_1extent__auto__changing__lines.html#a6004bba3802018de24ec1ae3fdf81e49',1,'nana::paint::helper::extent_auto_changing_lines::x()'],['../d4/d00/structnana_1_1detail_1_1msg__packet__tag.html#aba557973a9466ac5ab5a41f5841a8ddf',1,'nana::detail::msg_packet_tag::x()'],['../d0/d56/structnana_1_1detail_1_1messages_1_1caret.html#aad1a73968ec6bf000a022e48c5571a8e',1,'nana::detail::messages::caret::x()'],['../d6/dde/structnana_1_1detail_1_1messages_1_1move__window.html#a3a2cf6889cc3fceadef24339c19b33f6',1,'nana::detail::messages::move_window::x()'],['../d4/d4a/classnana_1_1area__rotator.html#a3345e895fa5a91350c8fee6e32cc9e84',1,'nana::area_rotator::x()']]],
  ['x11_5ferror_5fhandler',['X11_error_handler',['../d2/da8/namespacenana_1_1detail.html#ad7980438461ca9402c0551eefdb1f55b',1,'nana::detail']]],
  ['x11_5ffatal_5fhandler',['X11_fatal_handler',['../d2/da8/namespacenana_1_1detail.html#aee1718f4264b3d29929e0eb76128fade',1,'nana::detail']]],
  ['x_5fref',['x_ref',['../d4/d4a/classnana_1_1area__rotator.html#a5728d3144fddc4904de6e15f906f595f',1,'nana::area_rotator']]],
  ['xalloc',['xalloc',['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_ofstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::fstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_ostringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_ios::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ostringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_fstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::iostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ios_base::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wistream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::stringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wifstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_istream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::strstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_stringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wostringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::istrstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_ostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wiostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ofstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_istringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_ifstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::istringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::istream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ostrstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wfstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::basic_iostream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wofstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wstringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::wistringstream::xalloc()'],['http://en.cppreference.com/w/cpp/io/ios_base/xalloc.html',1,'std::ifstream::xalloc()']]],
  ['xdnd_5faction_5fcopy',['xdnd_action_copy',['../d4/da1/structnana_1_1detail_1_1atombase__tag.html#adb1e9a994955231fc2cb7dc020446ca4',1,'nana::detail::atombase_tag']]],
  ['xdnd_5faware',['xdnd_aware',['../d4/da1/structnana_1_1detail_1_1atombase__tag.html#ad5fada8e8bea261a01816f033f8c45be',1,'nana::detail::atombase_tag']]],
  ['xdnd_5fdrop',['xdnd_drop',['../d4/da1/structnana_1_1detail_1_1atombase__tag.html#ad89b9a063f891fc9b8d0b209619e1f0f',1,'nana::detail::atombase_tag']]],
  ['xdnd_5fenter',['xdnd_enter',['../d4/da1/structnana_1_1detail_1_1atombase__tag.html#ad069e8d6c43dbe1c5a6b9760b59c6467',1,'nana::detail::atombase_tag']]],
  ['xdnd_5ffinished',['xdnd_finished',['../d4/da1/structnana_1_1detail_1_1atombase__tag.html#a4a1b41c2705eda0b3a46a8d9d8c54272',1,'nana::detail::atombase_tag']]],
  ['xdnd_5fposition',['xdnd_position',['../d4/da1/structnana_1_1detail_1_1atombase__tag.html#a4c3970bc64cf680221743520b1b588b0',1,'nana::detail::atombase_tag']]],
  ['xdnd_5fselection',['xdnd_selection',['../d4/da1/structnana_1_1detail_1_1atombase__tag.html#a5a734da8a4a4d043eea7ab2f62c11b57',1,'nana::detail::atombase_tag']]],
  ['xdnd_5fstatus',['xdnd_status',['../d4/da1/structnana_1_1detail_1_1atombase__tag.html#afb635c12fd05411822cbd1b9a1d7e263',1,'nana::detail::atombase_tag']]],
  ['xdnd_5ftypelist',['xdnd_typelist',['../d4/da1/structnana_1_1detail_1_1atombase__tag.html#ab0beffd5746668ce9bb49a49dfe22cb5',1,'nana::detail::atombase_tag']]],
  ['xevent',['xevent',['../d4/d00/structnana_1_1detail_1_1msg__packet__tag.html#aacae9305e1c4af2858af0b06a1ac0746',1,'nana::detail::msg_packet_tag']]],
  ['xflags',['xflags',['../d4/d86/structgz__header__s.html#a40e35dc1a967c6537c6012cf5416210a',1,'gz_header_s']]],
  ['xsgetn',['xsgetn',['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::basic_filebuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::wstringbuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::stringbuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::wfilebuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::wstreambuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::strstreambuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::basic_stringbuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::basic_streambuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::filebuf::xsgetn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sgetn.html',1,'std::streambuf::xsgetn()']]],
  ['xsputn',['xsputn',['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::basic_filebuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::wstringbuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::stringbuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::wfilebuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::wstreambuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::strstreambuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::basic_stringbuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::basic_streambuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::filebuf::xsputn()'],['http://en.cppreference.com/w/cpp/io/basic_streambuf/sputn.html',1,'std::streambuf::xsputn()']]]
];
